name: call action from another repo
on:
  workflow_dispatch:

jobs:
  CallAction:
    runs-on: ubuntu-latest
    steps:
      - name: Call Demo Action
        uses: hello-world-docker-action@v1
        with:
          who-to-greet: 'friend'
