name: Reuse other workflows

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: 'matthew'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: "print current time"
        run: |
          echo "time was ${{ needs.call-workflow.output.current-time }} "
